package com.example.planetcorny.utilities;

import com.example.planetcorny.R;

public class Constants {
    public static final String KEY_PREFERENCE_NAME = "planetCornyPreference";
    public static final String KEY_IS_SIGNED_IN = "isSignedIn";
    public static final String KEY_USER_ID = "userId";
    public static final String KEY_USER_NAME = "userName";
    public static final String KEY_USER_EMAIL = "userEmail";

    // TABLE ACCOUNT
    public static final String TABLE_ACCOUNT = "account";
    public static final String COL_DISPLAY_NAME = "displayName";
    public static final String COL_EMAIL = "email";
    public static final String COL_PASSWORD = "password";

    // TABLE PLANET
    public static final String TABLE_PLANET = "planet";
    public static final String COL_PLANET_ID = "id";
    public static final String COL_PLANET_NAME = "name";
    public static final String COL_PLANET_IMAGE = "image";
    public static final String COL_PLANET_DESC = "description";
    public static final String COL_PLANET_DESC_DETAIL = "descDetail";

    public static final int[] imagePlanets = {
            R.drawable.ic_sun,
            R.drawable.ic_mercury, R.drawable.ic_neptune,
            R.drawable.ic_venus, R.drawable.ic_earth, R.drawable.ic_moon,
            R.drawable.ic_jupiter, R.drawable.ic_saturn,
            R.drawable.ic_uranus, R.drawable.ic_mars
    };

    public static final String[] namePlanets = {
            "Mặt trời", "Sao Thủy", "Sao Hải Vương", "Sao Kim",
            "Trái Đất", "Mặt Trăng", "Sao Mộc", "Sao Thổ",
            "Sao Thiên Vương", "Sao Hỏa"
    };

    public static final String[] descPlanets = {
            // Sun
            "Mặt trời là ngôi sao ở trung tâm của Hệ Mặt trời. Nó là một quả cầu plasma nóng gần như hoàn hảo, được nung nóng đến mức nóng sáng bởi các phản ứng tổng hợp hạt nhân trong lõi của nó, tỏa ra năng lượng chủ yếu dưới dạng ánh sáng nhìn thấy được và bức xạ hồng ngoại. Cho đến nay, nó vẫn nguồn năng lượng quan trọng nhất cho sự sống trên Trái đất. Đường kính của nó khoảng 1,39 triệu km (864.000 dặm), hay gấp 109 lần Trái đất. Khối lượng của nó gấp khoảng 330.000 lần Trái đất, chiếm khoảng 99,86% tổng khối lượng của Hệ Mặt trời.\nKhoảng ba phần tư khối lượng của Mặt trời bao gồm hydro (~73%); phần còn lại chủ yếu là heli (~25%), với một lượng nhỏ hơn nhiều các nguyên tố nặng hơn, bao gồm oxy, carbon, neon và sắt. ",

            // Mercury
            "Sao Thủy là hành tinh nhỏ nhất trong Hệ Mặt trời và gần Mặt trời nhất. Quỹ đạo của nó quay quanh Mặt trời mất 87,97 ngày Trái đất, ngắn nhất trong tất cả các hành tinh của Mặt trời. Nó được đặt theo tên của vị thần La Mã Mercurius (Mercury), vị thần thương mại , sứ giả của các vị thần và là người hòa giải giữa các vị thần và người phàm, tương ứng với thần Hy Lạp Hermes (Ἑρμῆς).\nGiống như sao Kim, sao Thủy quay quanh Mặt trời trong quỹ đạo của Trái đất với tư cách là một hành tinh kém hơn và khoảng cách biểu kiến ​​của nó so với Mặt trời khi nhìn từ Trái đất không bao giờ vượt quá 28°.\nKhoảng cách gần Mặt trời này có nghĩa là hành tinh này chỉ có thể được nhìn thấy ở gần đường chân trời phía tây sau khi mặt trời lặn hoặc đường chân trời phía đông trước khi mặt trời mọc, thường là vào lúc chạng vạng. Tại thời điểm này, nó có thể xuất hiện dưới dạng một vật thể giống như ngôi sao sáng nhưng thường khó quan sát hơn nhiều so với sao Kim.\nTừ Trái đất, hành tinh hiển thị bằng kính thiên văn toàn bộ phạm vi pha, tương tự như sao Kim và Mặt trăng, lặp lại trong chu kỳ đồng bộ của nó khoảng 116 ngày.",

            // Neptune
            "Sao Hải Vương là hành tinh thứ tám và xa nhất được biết đến tính từ Mặt trời. Trong Hệ Mặt trời, nó là hành tinh lớn thứ tư tính theo đường kính, hành tinh có khối lượng lớn thứ ba và là hành tinh khổng lồ đặc nhất.\n Nó gấp 17 lần khối lượng của Trái đất, nặng hơn một chút so với Sao Thiên Vương gần như song sinh của nó. Sao Hải Vương đặc hơn và nhỏ hơn về mặt vật lý so với Sao Thiên Vương vì khối lượng lớn hơn của nó gây ra lực nén nhiều hơn cho bầu khí quyển của nó. Hành tinh này quay quanh Mặt trời cứ sau 164,8 năm một lần với khoảng cách trung bình là 30,1 AU (4,5 tỷ km; 2,8 tỷ dặm).\nNó được đặt theo tên của vị thần biển La Mã và có ký hiệu thiên văn ♆, một phiên bản cách điệu của cây đinh ba của thần Neptune.",

            // Venus
            "Sao Kim là hành tinh thứ hai tính từ Mặt trời. Nó được đặt theo tên của nữ thần tình yêu và sắc đẹp La Mã. Là vật thể tự nhiên sáng nhất trên bầu trời đêm của Trái đất sau Mặt trăng, Sao Kim có thể đổ bóng và trong một số trường hợp hiếm hoi, có thể nhìn thấy được đối với Mặt trời. bằng mắt thường dưới ánh sáng ban ngày.\n Sao Kim nằm trong quỹ đạo của Trái đất và do đó dường như không bao giờ đi xa Mặt trời, lặn ở phía tây ngay sau khi hoàng hôn hoặc mọc ở phía đông một lúc trước bình minh. Sao Kim quay quanh Mặt trời cứ sau 224,7 Ngày Trái đất.\n Với chu kỳ quay là 243 ngày Trái đất, nó mất nhiều thời gian hơn để quay quanh trục của nó so với bất kỳ hành tinh nào khác trong Hệ Mặt trời và làm như vậy theo hướng ngược lại với tất cả ngoại trừ Sao Thiên Vương (có nghĩa là Mặt trời mọc ở phía tây và lặn ở phía đông). Sao Kim không có bất kỳ mặt trăng nào, một sự khác biệt mà nó chỉ chia sẻ với Sao Thủy trong số các hành tinh trong Hệ Mặt trời.",

            // Earth
            "Trái đất là hành tinh thứ ba tính từ Mặt trời và là vật thể thiên văn duy nhất được biết là có chứa và hỗ trợ sự sống. Khoảng 29,2% bề mặt Trái đất là đất liền bao gồm các lục địa và đảo. 70,8% còn lại được bao phủ bởi nước, chủ yếu là đại dương, biển, vịnh và các vùng nước mặn khác, mà còn bởi các hồ, sông và nước ngọt khác, cùng nhau tạo thành thủy quyển.\\n Phần lớn các vùng cực của Trái đất được bao phủ bởi băng. Lớp ngoài của Trái đất được chia thành nhiều mảng kiến tạo cứng di chuyển trên bề mặt trong nhiều triệu năm, trong khi phần bên trong của nó vẫn hoạt động với lõi bên trong bằng sắt rắn, lõi bên ngoài lỏng tạo ra từ trường của Trái đất và lớp phủ đối lưu thúc đẩy quá trình kiến tạo mảng",

            // Moon
            "Mặt trăng là vệ tinh tự nhiên duy nhất của Trái đất. Với đường kính khoảng một phần tư Trái đất (tương đương với chiều rộng của Australia), nó là vệ tinh tự nhiên lớn nhất trong Hệ Mặt trời so với kích thước của hành tinh của nó, là vệ tinh lớn thứ năm trong Hệ Mặt trời Hệ Mặt trời nói chung và lớn hơn bất kỳ hành tinh lùn nào.\nQuay quanh Trái đất ở khoảng cách trung bình là 384.400 km (238.900 dặm) hay khoảng 30 lần đường kính Trái đất, ảnh hưởng hấp dẫn của nó làm ngày của Trái đất kéo dài hơn một chút và là tác nhân chính gây ra thủy triều trên Trái đất . Mặt trăng được phân loại là một vật thể có khối lượng bằng hành tinh và là một thiên thể đá khác biệt, đồng thời không có bất kỳ bầu khí quyển, thủy quyển hay từ trường quan trọng nào.\nLực hấp dẫn bề mặt của nó bằng khoảng một phần sáu của Trái đất (0,1654 g); mặt trăng Io của sao Mộc là vệ tinh duy nhất trong Hệ Mặt trời được biết là có trọng lực và mật độ bề mặt cao hơn.",

            // Jupiter
            "Sao Mộc là hành tinh thứ năm tính từ Mặt trời và lớn nhất trong Hệ Mặt trời. Nó là một hành tinh khí khổng lồ có khối lượng (hơn) gấp hai lần rưỡi khối lượng của tất cả các hành tinh khác trong Hệ Mặt trời cộng lại, nhưng (một chút ) nhỏ hơn một phần nghìn khối lượng của Mặt trời.\nSao Mộc là vật thể tự nhiên sáng thứ ba trên bầu trời đêm của Trái đất sau Mặt trăng và Sao Kim. Nó đã được quan sát từ thời tiền sử và được đặt theo tên của vị thần La Mã, Sao Mộc, vua của các vị thần, vì kích thước khổng lồ của nó",

            // Saturn
            "Sao Thổ là hành tinh thứ sáu tính từ Mặt trời và lớn thứ hai trong Hệ Mặt trời, sau Sao Mộc. Nó là một hành tinh khí khổng lồ có bán kính trung bình bằng khoảng chín lần rưỡi so với Trái đất.\n Nó chỉ có bán kính bằng một phần tám mật độ trung bình của Trái đất; tuy nhiên, với thể tích lớn hơn, Sao Thổ có khối lượng lớn hơn 95 lần. Sao Thổ được đặt tên theo vị thần của cải và nông nghiệp của người La Mã; biểu tượng thiên văn của nó (♄) đại diện cho lưỡi liềm của vị thần.\n Người La Mã đặt tên cho ngày thứ bảy trong tuần Thứ Bảy, Sāturni diēs (\"Ngày của Sao Thổ\") không muộn hơn thế kỷ thứ 2 đối với hành tinh Sao Thổ.",

            // Uranus
            "Sao Thiên Vương là hành tinh thứ bảy tính từ Mặt trời. Tên của nó liên quan đến vị thần bầu trời của Hy Lạp, Uranus, theo thần thoại Hy Lạp, là ông cố của Ares (Mars), ông nội của Zeus (Jupiter) và cha của Cronus (Sao Thổ).\nNó có bán kính hành tinh lớn thứ ba và khối lượng hành tinh lớn thứ tư trong Hệ Mặt trời. Sao Thiên Vương có thành phần tương tự như Sao Hải Vương và cả hai đều có thành phần hóa học lớn khác với thành phần hóa học của các hành tinh khí khổng lồ lớn hơn Sao Mộc và Sao Thổ. Vì lý do này, các nhà khoa học thường phân loại Sao Thiên Vương và Sao Hải Vương là \"người khổng lồ băng\" để phân biệt chúng với các hành tinh khí khổng lồ khác.\nBầu khí quyển của Sao Thiên Vương tương tự như bầu khí quyển của Sao Mộc và Sao Thổ ở thành phần chính gồm hydro và heli, nhưng nó chứa nhiều \"băng\" hơn như nước, amoniac và mêtan, cùng với dấu vết của các hydrocacbon khác. Nó có bầu khí quyển hành tinh lạnh nhất trong Hệ Mặt trời.",

            // Mars
            "Sao Hỏa là hành tinh thứ tư tính từ Mặt trời và là hành tinh nhỏ thứ hai trong Hệ Mặt trời, chỉ lớn hơn sao Thủy. Trong tiếng Anh, Mars mang tên của vị thần chiến tranh La Mã và thường được gọi là \"Hành tinh Đỏ \".\nCái sau đề cập đến tác động của oxit sắt phổ biến trên bề mặt Sao Hỏa, khiến nó có màu đỏ đặc trưng giữa các thiên thể có thể nhìn thấy bằng mắt thường.\nSao Hỏa là một hành tinh đất đá có bầu khí quyển mỏng, với các đặc điểm bề mặt gợi nhớ đến các miệng hố va chạm trên Mặt trăng và các thung lũng, sa mạc và chỏm băng ở hai cực của Trái đất."
    };

    public static final String[] descDetailPlanet = {
            // Sun
            "Mặt Trời, hay Thái Dương (chữ Hán: 太陽), hay Nhật (chữ Hán: 日), là ngôi sao ở trung tâm Hệ Mặt Trời, chiếm khoảng 99,8% khối lượng của Hệ Mặt Trời.[6] Trái Đất và các thiên thể khác như các hành tinh, tiểu hành tinh, thiên thạch, sao chổi, và bụi quay quanh Mặt Trời. Khoảng cách trung bình giữa Mặt Trời và Trái Đất xấp xỉ 149,6 triệu kilômét (1 Đơn vị thiên văn AU) nên ánh sáng Mặt Trời cần 8 phút 20 giây mới đến được Trái Đất. Trong một năm, khoảng cách này thay đổi từ 147,1 triệu kilômét (0,9833 AU) ở điểm cận nhật (khoảng ngày 3 tháng 1), tới xa nhất là 152,1 triệu kilômét (1,017 AU) ở điểm viễn nhật (khoảng ngày 4 tháng 7).[7] Năng lượng Mặt Trời ở dạng ánh sáng hỗ trợ cho hầu hết sự sống trên Trái Đất thông qua quá trình quang hợp,[8] và điều khiển khí hậu cũng như thời tiết trên Trái Đất. Thành phần của Mặt Trời gồm hydro (khoảng 74% khối lượng, hay 92% thể tích), heli (khoảng 24% khối lượng, 7% thể tích), và một lượng nhỏ các nguyên tố khác, gồm sắt, nickel, oxy, silic, lưu huỳnh, magiê, carbon, neon, calci, và crom.[9] Mặt Trời có hạng quang phổ G2V. G2 có nghĩa nó có nhiệt độ bề mặt xấp xỉ 5.778 K (5.505 °C) khiến nó có màu trắng, và thường có màu vàng khi nhìn từ bề mặt Trái Đất bởi sự tán xạ khí quyển. Chính sự tán xạ này của ánh sáng ở giới hạn cuối màu xanh của quang phổ khiến bầu trời có màu xanh.[10] Quang phổ Mặt Trời có chứa các vạch ion hoá và kim loại trung tính cũng như các đường hydro rất yếu. V (số 5 La Mã) trong lớp quang phổ thể hiện rằng Mặt Trời, như hầu hết các ngôi sao khác, là một ngôi sao thuộc dãy chính. Điều này có nghĩa nó tạo ra năng lượng bằng tổng hợp hạt nhân của hạt nhân hydro thành heli. Có hơn 100 triệu ngôi sao lớp G2 trong Ngân Hà của chúng ta. Từng bị coi là một ngôi sao nhỏ và khá tầm thường nhưng thực tế theo hiểu biết hiện tại, Mặt Trời sáng hơn 85% các ngôi sao trong Ngân Hà với đa số là các sao lùn đỏ.[11][12]\n" +
                    "\n" +
                    "Quầng nóng của Mặt Trời liên tục mở rộng trong không gian và tạo ra gió Mặt Trời là các dòng hạt có vận tốc gấp 5 lần âm thanh - mở rộng nhật mãn (Heliopause) tới khoảng cách xấp xỉ 100 AU. Bong bóng trong môi trường liên sao được hình thành bởi gió mặt trời, nhật quyển (heliosphere) là cấu trúc liên tục lớn nhất trong Hệ Mặt Trời.[13][14]\n" +
                    "\n" +
                    "Mặt Trời hiện đang đi xuyên qua đám mây Liên sao Địa phương (Local Interstellar Cloud) trong vùng Bóng Địa phương (Local Bubble) mật độ thấp của khí khuếch tán nhiệt độ cao, ở vành trong của Nhánh Lạp Hộ của Ngân Hà, giữa Nhánh Anh Tiên và Nhánh Cung Thủ của Ngân Hà. Trong 50 hệ sao gần nhất bên trong 17 năm ánh sáng từ Trái Đất, Mặt Trời xếp hạng 4[15] về khối lượng như một ngôi sao cấp bốn (M = +4,83),[1][16] dù có một số giá trị cấp hơi khác biệt đã được đưa ra, ví dụ 4,85[17] và 4,81.[18] Mặt Trời quay quanh trung tâm của Ngân Hà ở khoảng cách xấp xỉ 24.000–26.000 năm ánh sáng từ trung tâm Ngân Hà, nói chung di chuyển theo hướng chòm sao Thiên Nga và hoàn thành một vòng trong khoảng 225–250 triệu năm (một năm ngân hà). Tốc độ trên quỹ đạo của nó được cho khoảng 250 ± 20, km/s nhưng một ước tính mới đưa ra con số 251 km/s.[19][20] Bởi Ngân Hà của chúng ta đang di chuyển so với Màn bức xạ vi sóng vũ trụ (CMB) theo hướng chòm sao Trường Xà với tốc độ 550 km/s, nên tốc độ chuyển động của nó so với CMB là khoảng 370 km/s theo hướng chòm sao Cự Tước hay Sư Tử.[21]",

            // Mercury
            "Sao Thủy (Mercury) hay Thủy tinh (chữ Hán: 水星) là hành tinh nhỏ nhất và gần Mặt Trời nhất trong tám hành tinh thuộc Hệ Mặt Trời,[a] với chu kỳ quỹ đạo bằng khoảng 88 ngày Trái Đất. Nhìn từ Trái Đất, hành tinh hiện lên với chu kỳ giao hội trên quỹ đạo bằng xấp xỉ 116 ngày, và nhanh hơn hẳn những hành tinh khác. Tốc độ chuyển động nhanh này đã khiến người La Mã đặt tên hành tinh là Mercurius, vị thần liên lạc và đưa tin một cách nhanh chóng. Trong thần thoại Hy Lạp tên của vị thần này là Hermes (Ερμής). Tên tiếng Việt của hành tinh này dựa theo tên do Trung Quốc đặt, chọn theo hành thủy trong ngũ hành.\n" +
                    "\n" +
                    "Do hành tinh hầu như không có khí quyển để giữ lại nhiệt lượng, bề mặt Sao Thủy trải qua sự biến đổi nhiệt độ lớn nhất trong số các hành tinh, thay đổi từ 100 K (−173 °C; −280 °F) vào ban đêm tới 700 K (427 °C; 800 °F) vào ban ngày. Trục quay của Sao Thủy có độ nghiêng nhỏ nhất trong Hệ Mặt Trời (khoảng 1⁄30 độ), nhưng hành tinh lại có độ lệch tâm quỹ đạo lớn nhất.[a] Tại viễn điểm quỹ đạo, Sao Thủy ở cách xa Mặt Trời hơn 1,5 lần khi so với hành tinh ở cận điểm quỹ đạo. Bề mặt hành tinh có rất nhiều hố va chạm nhìn trông giống như bề mặt của Mặt Trăng, và hành tinh không còn hoạt động địa chất trong hàng tỷ năm trước.\n" +
                    "\n" +
                    "Trên Sao Thủy không có sự biến đổi thời tiết theo mùa như ở các hành tinh khác bởi vì nó không có bầu khí quyển đáng kể. Hành tinh bị khóa thủy triều với Mặt Trời do đó nó quay trên quỹ đạo rất khác so với các hành tinh khác. Khi lấy các ngôi sao cố định làm điểm mốc, nó tự quay được chính xác ba vòng trong hai chu kỳ quỹ đạo quanh Mặt Trời [b]. Khi nhìn từ Mặt Trời, trong hệ quy chiếu quay cùng với chuyển động quỹ đạo, hành tinh hiện lên chỉ quay quanh trục một lần trong hai \"năm\" Sao Thủy. Do vậy nếu có người đứng trên Sao Thủy họ chỉ nhận thấy 1 ngày trong 2 năm.\n" +
                    "\n" +
                    "Bởi vì quỹ đạo Thủy Tinh nằm bên trong quỹ đạo Trái Đất (và của Sao Kim), khi nhìn từ Trái Đất hành tinh có lúc hiện lên vào buổi sáng hoặc vào buổi tối, nhưng không bao giờ có thể nhìn thấy lúc nửa đêm. Tương tự như Sao Kim và Mặt Trăng, hành tinh cũng có các pha quan sát khi nó di chuyển trên quỹ đạo. Sao Thủy không có một vệ tinh tự nhiên nào. Độ sáng biểu kiến của Sao Thủy thay đổi từ −2,0 đến 5,5; nhưng vì quá gần Mặt Trời nên nếu quan sát hành tinh này qua kính viễn vọng rất khó khăn và ít khi thực hiện được.\n" +
                    "\n" +
                    "Hai phi thuyền đã ghé thăm sao Thủy: Mariner 10 bay vào năm 1974 và 1975; và MESSENGER, được phóng lên vào năm 2004, đã quay quanh sao Thủy hơn 4.000 lần trong vòng bốn năm trước khi cạn kiệt nguồn nhiên liệu và rơi vào bề mặt hành tinh này vào ngày 30 tháng 4 năm 2015.[11][12][13] Tàu vũ trụ BepiColombo lập kế hoạch bay đến Sao Thủy vào năm 2025.",

            // Neptune
            "Sao Hải Vương (Neptune) hay Hải Vương tinh (chữ Hán: 海王星) là hành tinh thứ tám và xa nhất tính từ Mặt Trời trong Hệ Mặt Trời. Nó là hành tinh lớn thứ tư về đường kính và lớn thứ ba về khối lượng. Sao Hải Vương có khối lượng riêng lớn nhất trong số các hành tinh khí trong hệ Mặt trời. Sao Hải Vương có khối lượng gấp 17 lần khối lượng của Trái Đất và hơi lớn hơn khối lượng của Sao Thiên Vương (xấp xỉ bằng 15 lần của Trái Đất).[11] Sao Hải Vương quay trên quỹ đạo quanh Mặt Trời ở khoảng cách trung bình 30,1 AU, bằng khoảng 30 lần khoảng cách Trái Đất - Mặt Trời. Sao Hải Vương được đặt tên theo vị thần biển cả của người La Mã (Neptune). Nó có ký hiệu thiên văn là ♆, là biểu tượng cách điệu cây đinh ba của thần Neptune hoặc chữ cái psi của Hy Lạp.\n" +
                    "\n" +
                    "Sao Hải Vương là hành tinh đầu tiên được tìm thấy bằng tính toán lý thuyết. Dựa vào sự nhiễu loạn bất thường của quỹ đạo Sao Thiên Vương, nhà thiên văn Alexis Bouvard đã kết luận rằng quỹ đạo của nó bị nhiễu loạn do tương tác hấp dẫn với một hành tinh nào đó. Vào ngày 23 tháng 9 năm 1846,[1] nhà thiên văn Johann Galle đã phát hiện ra Sao Hải Vương ở vị trí lệch 1 độ so với tiên đoán của Urbain Le Verrier. Sau đó ít lâu, người ta cũng khám phá ra Triton, vệ tinh lớn nhất của sao Hải Vương, trong khi 13 vệ tinh còn lại của nó chỉ được phát hiện trong thế kỷ XX. Cho tới nay, tàu không gian Voyager 2 là tàu duy nhất bay qua Sao Hải Vương vào ngày 25 tháng 8 năm 1989.\n" +
                    "\n" +
                    "Sao Hải Vương có cấu tạo tương tự như Sao Thiên Vương, nhưng lại khác biệt với những hành tinh khí khổng lồ như Sao Mộc và Sao Thổ. Khí quyển của sao Hải Vương chứa thành phần cơ bản là hydro và heli, cùng một số ít các hydrocarbon và có lẽ cả nitơ, tương tự như của Sao Mộc hay Sao Thổ. Tuy nhiên khí quyển của nó chứa tỷ lệ lớn hơn các phân tử \"băng\" như nước, amonia, và methan. Do đó các nhà thiên văn thỉnh thoảng phân loại Sao Thiên Vương và Sao Hải Vương thành các hành tinh băng đá khổng lồ để nhấn mạnh sự khác biệt này.[12] Bên trong Sao Hải Vương chứa chủ yếu băng và đá, giống như Sao Thiên Vương.[13] Lõi hành tinh có thể có bề mặt tuy rắn nhưng nhiệt độ của nó có thể cao tới hàng nghìn độ và áp suất rất lớn.[14] Khí methan trong tầng ngoài khí quyển là nguyên nhân Sao Hải Vương hiện lên với màu xanh lam.[15]\n" +
                    "\n" +
                    "Trái ngược với bầu khí quyển mờ đặc và gần như đồng màu của Sao Thiên Vương, khí quyển của Sao Hải Vương có những vùng hoạt động mạnh và dễ nhận thấy. Năm 1989, tàu Voyager 2 khi bay qua Sao Hải Vương đã chụp được hình ảnh của Vết Tối Lớn trên bán cầu nam có kích thước tương đương với Vết Đỏ Lớn của Sao Mộc. Những vùng hoạt động thời tiết này được duy trì bởi những cơn gió với tốc độ lên tới 2.100 kilômét trên giờ, mạnh nhất trên khí quyển trong các hành tinh thuộc Hệ Mặt Trời.[16] Do cách rất xa Mặt Trời nên lớp khí quyển ngoài cùng của Sao Hải Vương là một trong những nơi lạnh nhất trong Hệ Mặt Trời. Nhiệt độ của những đám mây trên cao khoảng 55 K (-218 °C) trong khi nhiệt độ tại lõi hành tinh xấp xỉ 5.400 K (5.000 °C).[17][18] Sao Hải Vương có một hệ thống vành đai mờ và rời rạc (hay những cung), được phát hiện trong thập niên 1960 nhưng chỉ được xác nhận vào năm 1989 bởi Voyager 2.",

            // Venus
            "Sao Kim hay Kim tinh (chữ Hán: 金星), còn gọi là sao Thái Bạch (太白), Thái Bạch Kim tinh (太白金星) (tiếng Anh: Venus) là hành tinh thứ 2 trong hệ Mặt Trời, tự quay quanh nó với chu kỳ 224,7 ngày Trái Đất.[10] Xếp sau Mặt Trăng, nó là thiên thể tự nhiên sáng nhất trong bầu trời tối, với cấp sao biểu kiến bằng −4.6, đủ sáng để tạo nên bóng trên mặt nước.[12] Bởi vì Sao Kim là hành tinh phía trong tính từ Trái Đất, nó không bao giờ xuất hiện trên bầu trời mà quá xa Mặt Trời: góc ly giác đạt cực đại bằng 47,8°. Sao Kim đạt độ sáng lớn nhất ngay sát thời điểm hoàng hôn hoặc bình minh, do vậy mà dân gian còn gọi là sao Hôm, khi hành tinh này hiện lên lúc hoàng hôn, và sao Mai, khi hành tinh này hiện lên lúc bình minh.\n" +
                    "\n" +
                    "Sao Kim được xếp vào nhóm hành tinh đất đá và đôi khi người ta còn coi nó là \"hành tinh chị em\" với Trái Đất do kích cỡ, gia tốc hấp dẫn, tham số quỹ đạo gần giống với Trái Đất. Tuy nhiên, người ta đã chỉ ra rằng nó rất khác Trái Đất trên những mặt khác. Sao Kim bị bao bọc bởi lớp mây dày có tính phản xạ cao chứa axít sunfuric,[13] và khiến chúng ta không thể quan sát bề mặt của nó dưới bước sóng ánh sáng khả kiến. Mật độ không khí trong khí quyển của nó lớn nhất trong số bốn hành tinh đất đá, thành phần chủ yếu là cacbon dioxide. Áp suất khí quyển tại bề mặt hành tinh cao gấp 92 lần so với của Trái Đất. Với nhiệt độ bề mặt trung bình bằng 735 K (462 °C), Sao Kim là hành tinh nóng nhất trong Hệ Mặt Trời. Nó không có chu trình cacbon để đưa cacbon trở lại đá và đất trên bề mặt, do vậy không thể có một tổ chức sống hữu cơ nào có thể hấp thụ nó trong sinh khối. Một số nhà khoa học từng cho rằng Sao Kim đã có những đại dương trong quá khứ,[14] nhưng đã bốc hơi khi nhiệt độ hành tinh tăng lên do hiệu ứng nhà kính mất kiểm soát.[15] Nước có thể đã bị quang ly, và bởi vì không có từ quyển hành tinh, hydro tự do có thể thoát vào vũ trụ bởi tác động của gió Mặt Trời.[16] Toàn bộ bề mặt của Sao Kim là một hoang mạc khô cằn với đá và bụi và có lẽ vẫn còn núi lửa hoạt động trên hành tinh này.",

            // Earth
            "Trái Đất, hay còn gọi là Địa Cầu (chữ Hán: 地球, tiếng Anh: Earth), là hành tinh thứ ba tính từ Mặt Trời, đồng thời cũng là hành tinh lớn nhất trong các hành tinh đất đá của hệ Mặt Trời xét về bán kính, khối lượng và mật độ của vật chất. Trái Đất còn được biết tên với các tên gọi \"hành tinh xanh\",[note 2] là nhà của hàng triệu loài sinh vật,[13] trong đó có con người và cho đến nay nó là nơi duy nhất trong vũ trụ được biết đến là có sự sống. Hành tinh này được hình thành cách đây khoảng 4,55 tỷ năm[14][15][16][17] và sự sống xuất hiện trên bề mặt của nó khoảng 1 tỷ năm trước. Kể từ đó, sinh quyển, khí quyển của Trái Đất và các điều kiện vô cơ khác đã thay đổi đáng kể, tạo điều kiện thuận lợi cho sự phổ biến của các vi sinh vật ưa khí cũng như sự hình thành của tầng ôzôn-lớp bảo vệ quan trọng, cùng với từ trường của Trái Đất, đã ngăn chặn các bức xạ có hại và chở che cho sự sống.[18] Các đặc điểm vật lý của Trái Đất cũng như lịch sử địa lý hay quỹ đạo, cho phép sự sống tồn tại trong thời gian qua. Người ta ước tính rằng Trái Đất chỉ còn có thể hỗ trợ sự sống thêm 1,5 tỷ năm nữa, trước khi kích thước của Mặt Trời tăng lên (trở thành sao khổng lồ đỏ) và tiêu diệt hết sự sống.[19]\n" +
                    "\n" +
                    "Bề mặt Trái Đất được chia thành các mảng kiến tạo, chúng di chuyển từ từ trên bề mặt Trái Đất trong hàng triệu năm. Khoảng hơn 70% bề mặt Trái Đất được bao phủ bởi các đại dương nước mặn, phần còn lại là các lục địa và các đảo. Nước là thành phần rất cần thiết cho sự sống và cho đến nay con người vẫn chưa phát hiện thấy sự tồn tại của nó trên bề mặt của bất kì hành tinh nào khác ngoại trừ sao Hỏa (Hỏa Tinh) là có nước bị đóng băng ở hai cực.[note 3][note 4] Tuy nhiên, người ta có chứng cứ xác định nguồn nước có ở Sao Hỏa trong quá khứ, và có thể tồn tại cho tới ngày nay.[20] Lõi của Trái Đất vẫn hoạt động được bao bọc bởi lớp manti rắn dày, lớp lõi ngoài lỏng tạo ra từ trường và lõi sắt trong rắn.[23]\n" +
                    "\n" +
                    "Trái Đất tương tác với các vật thể khác trong không gian bao gồm Mặt Trời và Mặt Trăng. Hiện quãng thời gian Trái Đất di chuyển hết một vòng quanh Mặt Trời bằng 365,2564 lần quãng thời gian nó tự quay một vòng quanh trục của mình. Khoảng thời gian này bằng với một năm thiên văn tức 365,2564 ngày trong dương lịch.[note 5] Trục tự quay của Trái Đất nghiêng một góc bằng 23,44° so với trục vuông góc với mặt phẳng quỹ đạo,[24] tạo ra sự thay đổi mùa trên bề mặt của Trái Đất trong một năm chí tuyến. Mặt Trăng, vệ tinh tự nhiên duy nhất của Trái Đất, đồng thời cũng là nguyên nhân chính gây ra hiện tượng thủy triều đại dương, bắt đầu quay quanh Trái Đất từ 4,53 tỷ năm trước, vẫn giữ nguyên góc quay ban đầu theo thời gian nhưng đang chuyển động chậm dần lại. Trong khoảng từ 4,1 đến 3,8 tỷ năm trước, sự va đập của các thiên thạch trong suốt thời kì đã tạo ra những sự thay đổi đáng kể trên bề mặt Mặt Trăng.\n" +
                    "\n" +
                    "Cả tài nguyên khoáng sản lẫn các sản phẩm của sinh quyển Trái Đất được sử dụng để cung cấp cho cuộc sống của con người. Dân cư được chia thành hơn hàng trăm quốc gia độc lập, có quan hệ với nhau thông qua các hoạt động ngoại giao, du lịch, thương mại, quân sự. Văn hóa loài người đã phát triển tạo nên nhiều cách nhìn về Trái Đất bao gồm việc nhân cách hóa Trái Đất như một vị thần, niềm tin vào một Trái Đất phẳng hoặc Trái Đất là trung tâm của cả vũ trụ, và một quan điểm nhìn hiện đại hơn như Trái Đất là một môi trường thống nhất cần có sự định hướng.",

            // Moon
            "Mặt Trăng là vệ tinh tự nhiên duy nhất của Trái Đất.[3]:14[↓ 1] Với độ sáng ở bầu trời chỉ sau Mặt Trời,[6]tr.120 Mặt Trăng đã được con người biết đến từ thời tiền sử.[24] Mặt Trăng có hình cầu[25]tr.223 với chiều rộng bằng khoảng 27% Trái Đất và khối lượng bằng khoảng 1,23% Trái Đất.[6]tr.304 Bề mặt Mặt Trăng chứa nhiều khoáng silicat và không có khí quyển, thủy quyển, hay từ quyển đáng kể.[6][26]tr.304,309\n" +
                    "\n" +
                    "Giả thuyết về sự hình thành của Mặt Trăng được chấp nhận rộng rãi nhất cho rằng: cách đây hơn 4,5 tỷ năm,[27] không lâu sau khi Trái Đất hình thành,[28] Mặt Trăng được hình thành từ các vụn văng ra sau một vụ va chạm giữa Trái Đất và một thiên thể khác mang tên Theia[↓ 5] cỡ Sao Hỏa.[30][31]\n" +
                    "\n" +
                    "Mặt Trăng ở trong quỹ đạo đồng bộ với Trái Đất, tức là chu kỳ tự quay của Mặt Trăng bằng với chu kỳ quay quanh Trái Đất, khoảng 27,3 ngày, do đó nó luôn quay một mặt về phía Trái Đất, là mặt gần.[6]tr.123 Do hiện tượng bình động nên quan sát từ Trái Đất qua nhiều thời điểm, với mỗi thời điểm ở góc nhìn hơi khác, sẽ thấy tổng cộng nhiều hơn một nửa diện tích Mặt Trăng (59%).[3]:18 Các pha Mặt Trăng, từ trăng tròn đến trăng tối, tuần hoàn theo chu kỳ giao hội 29,5 ngày,[6]tr.123 tạo thành cơ sở cho lịch Mặt Trăng (âm lịch).[25]tr.208-209 Đường kính góc của Mặt Trăng trên bầu trời tương đương với Mặt Trời, khoảng hơn nửa độ, do đó Mặt Trăng che kín Mặt Trời trong nhật thực toàn phần.[25]tr.253 Lực hấp dẫn của Mặt Trăng gây ra thủy triều trên đại dương ở Trái Đất, đồng thời gây ra hiệu ứng tương tự cho phần vỏ và lõi đất đá của Trái Đất, và làm cho một ngày ở Trái Đất dài hơn một chút.[6]tr.125-128 Khoảng cách trung bình từ Mặt Trăng đến Trái Đất là khoảng 384000 km,[6]tr.19 tương đương 1,28 giây ánh sáng, hay khoảng 30 lần đường kính Trái Đất.[25]tr.223 Trong tương lai xa, khoảng cách từ Mặt Trăng đến Trái Đất sẽ tăng dần, do hiệu ứng thủy triều, và Mặt Trăng sẽ xuất hiện nhỏ dần.[6]tr.128\n" +
                    "\n" +
                    "Trong Hệ Mặt Trời, Mặt Trăng là vệ tinh tự nhiên lớn thứ năm.[6]tr.410 Nếu xét về tỷ lệ kích thước so với hành tinh mà nó quay quanh thì Mặt Trăng đạt tỷ lệ này cao nhất trong Hệ Mặt Trời.[6]tr.388,410,412[↓ 6] Bề mặt Mặt Trăng có các biển Mặt Trăng là các vùng vật chất tối màu có nguồn gốc từ hoạt động núi lửa cũ, nằm chủ yếu ở mặt gần, giữa các vùng vỏ cũ cao sáng màu có rất nhiều hố va chạm.[6]tr.310-312 Các hố va chạm trên Mặt Trăng được bảo quản tốt và cung cấp nhiều thông tin về quá khứ của Hệ Mặt Trời.[6]tr.303 Trọng trường ở bề mặt Mặt Trăng bằng khoảng 1/6 so với Trái Đất.[25]tr.226 Nhiệt độ thay đổi mạnh theo điều kiện nhận ánh sáng Mặt Trời, trung bình từ khoảng -180°C vào ban đêm đến trên 100 °C vào ban ngày tại xích đạo.[21] Tồn tại hàng trăm tỷ tấn nước đá ở đáy những hố va chạm gần cực, nơi vĩnh viễn không nhận được ánh nắng.[6]tr.309\n" +
                    "\n" +
                    "Chương trình Luna của Liên Xô đã đưa được vật thể nhân tạo đầu tiên lên Mặt Trăng là tàu không người lái Luna 2, một tàu vũ trụ được chủ đích cho đâm xuống bề mặt Mặt Trăng vào tháng 9 năm 1959.[32]tr.12-13 Sau đó vào năm 1966, tàu Luna 9 đã đổ bộ an toàn lên Mặt Trăng.[6]tr.305 Chương trình Apollo của Hoa Kỳ những năm tiếp theo đã giúp con người lên Mặt Trăng, với Apollo 8 năm 1968 lần đầu đưa người bay quanh Mặt Trăng, rồi Apollo 11 vào tháng 7 năm 1969 cùng 5 chuyến bay khác sau đó đã hạ cánh với con người và thiết bị lên thiên thể này.[6]tr.305-306 Các chuyến thám hiểm này đã mang về Trái Đất đá Mặt Trăng được dùng để nghiên cứu và bổ sung kiến thức về Mặt Trăng cũng như nguồn gốc hình thành của nó.[6]tr.306 Từ sau chuyến bay Apollo 17 năm 1972 đến hiện tại, chỉ có các tàu không người lái đến thám hiểm Mặt Trăng.[6]tr.307\n" +
                    "\n" +
                    "Sự hiện diện của Mặt Trăng trên bầu trời, theo chu kỳ pha Mặt Trăng, đã để lại dấu ấn trong xã hội và văn hóa của loài người.[6]tr.120 Ảnh hưởng trong văn hóa xã hội thể hiện ở ngôn ngữ,[6]tr.123 hệ thống âm lịch,[25]tr.208-209 nghệ thuật,[33] và thần thoại.[29]",

            // Jupiter
            "Sao Mộc (Jupiter) hay Mộc tinh (chữ Hán: 木星) là hành tinh thứ năm tính từ Mặt Trời và là hành tinh lớn nhất trong Hệ Mặt Trời.[12] Nó là hành tinh khí khổng lồ với khối lượng bằng một phần nghìn của Mặt Trời nhưng bằng hai lần rưỡi tổng khối lượng của tất cả các hành tinh khác trong Hệ Mặt Trời cộng lại. Sao Mộc được xếp vào nhóm hành tinh khí khổng lồ cùng với Sao Thổ (Sao Thiên Vương và Sao Hải Vương được xếp vào hành tinh băng khổng lồ). Hai hành tinh này đôi khi được gọi là hành tinh kiểu Sao Mộc hoặc hành tinh vòng ngoài. Các nhà thiên văn học cổ đại đã biết đến hành tinh này,[13] và gắn với thần thoại và niềm tin tôn giáo trong nhiều nền văn hóa. Người La Mã đặt tên hành tinh theo tên của vị thần Jupiter, vị thần quan trọng nhất trong số các vị thần.[14] Tên gọi trong tiếng Trung Quốc, tiếng Triều Tiên, tiếng Nhật và tiếng Việt của hành tinh này được đặt dựa vào hành \"mộc\" trong ngũ hành. Khi nhìn từ Trái Đất, Sao Mộc có cấp sao biểu kiến −2,94, đủ sáng để tạo bóng; và là thiên thể sáng thứ ba trên bầu trời đêm sau Mặt Trăng và Sao Kim. (Sao Hỏa hầu như sáng bằng Sao Mộc khi Sao Hỏa ở những vị trí xung đối trên quỹ đạo của nó với Trái Đất).\n" +
                    "\n" +
                    "Sao Mộc chứa chủ yếu hydro và heli - chiếm một phần tư khối lượng của nó, mặc dù heli chỉ chiếm một phần mười số lượng phân tử. Có thể có một lõi đá trong hành tinh chứa các nguyên tố nặng hơn,[15] nhưng không giống như những hành tinh khí khổng lồ khác, Sao Mộc không có một bề mặt rắn định hình. Bởi vì có tốc độ tự quay nhanh, hình dạng của hành tinh có hình phỏng cầu dẹt (nó hơi phình ra tại xích đạo). Lớp khí quyển ngoài cùng hiện lên với nhiều dải mây ở những độ cao khác nhau, do kết quả của hiện tượng nhiễu loạn khí động và tương tác với những cơn bão tại biên. Một đặc điểm nổi bật trên ảnh chụp của nó đó là Vết Đỏ Lớn, một cơn bão khổng lồ được biết đến tồn tại ít nhất từ thế kỷ 17 khi các nhà thiên văn lần đầu tiên quan sát nó bằng kính thiên văn. Bao quanh Mộc Tinh là một hệ thống vành đai mờ nhạt cũng như từ quyển mạnh. Có ít nhất 80 vệ tinh tự nhiên quay quanh nó,[16] bao gồm bốn vệ tinh lớn nhất gọi là các vệ tinh Galileo do nhà bác học Galileo Galilei lần đầu tiên quan sát năm 1610. Ganymede, vệ tinh lớn nhất, có đường kính lớn hơn Sao Thủy.\n" +
                    "\n" +
                    "Đã có một vài tàu không gian thám hiểm đến Sao Mộc, bao gồm tàu Pioneer và Voyager trong các phi vụ bay ngang qua và sau đó tàu Galileo bay quay hành tinh này. Con tàu gần đây nhất bay qua Sao Mộc trên hành trình đến Sao Diêm Vương - tàu New Horizons bay qua vào cuối 2007. Con tàu sử dụng sự hỗ trợ của hấp dẫn từ Sao Mộc nhằm tăng tốc độ của nó. Hiện nay tàu Juno của NASA đã đến vào ngày 5 tháng 7 năm 2016.[17] Trong tương lai có phi vụ của ESA đến thám hiểm các vệ tinh Galileo nói chung và Europa nói riêng.",

            // Saturn
            "Sao Thổ (Saturn) (chữ Hán: 土星) là hành tinh thứ sáu tính theo khoảng cách trung bình từ Mặt Trời và là hành tinh lớn thứ hai về đường kính cũng như khối lượng, sau Sao Mộc trong Hệ Mặt Trời. Tên tiếng Anh của hành tinh mang tên thần Saturn trong thần thoại La Mã, ký hiệu thiên văn của hành tinh là (♄) thể hiện cái liềm của thần. Sao Thổ là hành tinh khí khổng lồ với bán kính trung bình bằng 9 lần của Trái Đất.[14][15] Tuy khối lượng của hành tinh cao gấp 95 lần khối lượng của Trái Đất nhưng với thể tích lớn hơn 763 lần, khối lượng riêng trung bình của Sao Thổ chỉ bằng một phần tám so với của Trái Đất.[16][17][18]\n" +
                    "\n" +
                    "Cấu trúc bên trong của Sao Thổ có lẽ bao gồm một lõi sắt, nikel và đá (hợp chất silic và oxy), bao quanh bởi một lớp dày hiđrô kim loại, một lớp trung gian giữa hiđrô lỏng với heli lỏng và bầu khí quyển bên trên cùng.[19] Hình ảnh hành tinh có màu sắc vàng nhạt là do sự có mặt của các tinh thể amonia trong tầng thượng quyển. Dòng điện bên trong lớp hiđrô kim loại là nguyên nhân Sao Thổ có một từ trường hành tinh với cường độ hơi yếu hơn so với từ trường của Trái Đất và bằng một phần mười hai so với cường độ từ trường của Sao Mộc.[20] Lớp khí quyển bên trên cùng hành tinh có những màu đồng nhất và hiện lên dường như yên ả so với bầu khí quyển hỗn loạn của Sao Mộc, mặc dù nó cũng có những cơn bão mạnh. Tốc độ gió trên Sao Thổ có thể đạt tới 1.800 km/h, nhanh hơn trên Sao Mộc, nhưng không nhanh bằng tốc độ gió trên Sao Hải Vương.[21][22]\n" +
                    "\n" +
                    "Sao Thổ có một hệ thống vành đai bao gồm chín vành chính liên tục và ba cung đứt đoạn, chúng chứa chủ yếu hạt băng với lượng nhỏ bụi và đá. Sao Thổ có 82 vệ tinh tự nhiên đã biết[23]; trong đó 53 vệ tinh đã được đặt tên. Số lượng vệ tinh này không bao gồm hàng trăm tiểu vệ tinh (\"moonlet\") bên trong vành đai. Titan là vệ tinh lớn nhất của Sao Thổ và là vệ tinh lớn thứ hai trong Hệ Mặt Trời, nó cũng lớn hơn cả Sao Thủy và là vệ tinh tự nhiên duy nhất trong Hệ Mặt Trời có bầu khí quyển dày đặc.[24]",

            // Uranus
            "Sao Thiên Vương (Uranus) hay Thiên Vương tinh (chữ Hán: 天王星) là hành tinh thứ bảy tính từ Mặt Trời; là hành tinh có bán kính lớn thứ ba và có khối lượng lớn thứ tư trong Hệ Mặt Trời. Sao Thiên Vương có thành phần tương tự như Sao Hải Vương. Cả hai có thành phần hóa học khác so với hai hành tinh khí khổng lồ lớn hơn là Sao Mộc và Sao Thổ. Vì vậy, các nhà thiên văn thỉnh thoảng đưa các hành tinh này vào danh sách \"hành tinh băng khổng lồ\". Khí quyển của Sao Thiên Vương tương tự như của Sao Mộc và Sao Thổ về thành phần cơ bản như hiđrô và heli. Khác là chúng chứa nhiều hợp chất dễ bay hơi như nước, amonia và methan cùng với lượng nhỏ hydrocarbon.[9] Hành tinh này có bầu khí quyển lạnh nhất trong số các hành tinh trong Hệ Mặt Trời, với nhiệt độ cực tiểu bằng 49 K (−224 °C). Nó có cấu trúc tầng mây phức tạp. Khả năng những đám mây thấp nhất chứa chủ yếu nước trong khi methan lại chiếm chủ yếu trong những tầng mây phía trên.[9] Ngược lại, cấu trúc bên trong Sao Thiên Vương chỉ chứa chủ yếu một lõi băng và đá.[8]\n" +
                    "\n" +
                    "Giống như những hành tinh khí khổng lồ khác, Sao Thiên Vương có một hệ thống vành đai, từ quyển và rất nhiều vệ tinh tự nhiên. Hệ thống Sao Thiên Vương có cấu trúc độc nhất bởi vì trục tự quay của nó bị nghiêng rất lớn, gần như song song với mặt phẳng quỹ đạo của hành tinh. Do vậy cực bắc và cực nam của hành tinh này nằm gần như tại vị trí xích đạo so với những hành tinh khác.[14] Năm 1986, những ảnh chụp của tàu không gian Voyager 2 cho thấy Sao Thiên Vương qua ánh sáng khả kiến hiện lên với một màu gần như đồng nhất mà không có các dải mây hay cơn bão như những hành tinh khí khổng lồ khác.[14] Các nhà thiên văn thực hiện quan sát từ mặt đất phát hiện ra dấu hiệu của sự thay đổi mùa và sự gia tăng hoạt động thời tiết trong những năm gần đây khi nó tiếp cận đến vị trí điểm phân trên quỹ đạo. Tốc độ gió trên Sao Thiên Vương đạt tới 250 mét trên giây (900 km/h).[15]",

            // Mars
            "Sao Hỏa hay Hỏa tinh (chữ Hán: 火星, tiếng Anh: Mars) là hành tinh thứ tư tính từ Mặt Trời ra. Sao Hoả là hành tinh có kích thước bé thứ hai trong Hệ Mặt Trời, chỉ lớn hơn Sao Thủy. Sao Hỏa là hành tinh đất đá với bầu khí quyển mỏng, với nhiều hố va chạm, núi lửa, thung lũng, sa mạc và chỏm băng ở trên bề mặt như là ở trên Trái Đất. Sao Hoả hay được gọi ví von là \"Hành tinh Đỏ\" do bề mặt hành tinh chứa rất nhiều sắt(III) oxide có màu đỏ cam.[16]\n" +
                    "\n" +
                    "Độ dài ngày và các mùa và trên sao Hỏa tương đối giống Trái Đất, do Sao Hoả quay quanh chính nó trong 24,5 giờ và cả hai hành tinh đều có trục quay nghiêng. Ở bề mặt Sao Hoả có Olympus Mons là ngọn núi cao nhất và Valles Marineris (nhin như đường rạch dài) là hẻm núi dài nhất trong Hệ Mặt Trời. Ở bán cầu Bắc bề mặt Sao Hoả bằng phẳng bất thường, bao phủ tới 40% bề mặt hành tinh và có tên gọi là lòng chảo Borealis. Hai vệ tinh tự nhiên của Sao Hoả có tên là Phobos và Deimos; chúng có hình thù méo mó và kích cỡ nhỏ so với các vệ tinh khác.[17][18]\n" +
                    "\n" +
                    "Hiện tại, con người thám hiểm Sao Hỏa bằng rôbốt và vệ tinh nhân tạo. Năm 1965, Mariner 4 là tàu vũ trụ đầu tiên của NASA tiệp cận Sao Hoả, và năm 1976 buồng đáp của Viking 1 lần đầu chụp ảnh của bề mặt hành tinh đỏ. Tính đến nay, hai quốc gia đã đáp rôbốt tự lái đến Sao Hoả: Hoa Kì với rôbốt Sojourner đáp xuống năm 1997 và Trung Quốc với rôbốt Zhurong (của Thiên vấn 1) đáp xuống năm 2021. Theo kế hoạch, năm 2026 một tên lửa mini sẽ phóng, đáp, và mang đất đá từ Sao Hoả về Trái Đất. Tàu Rosalind Franklin của Cơ quan Vũ trụ châu Âu theo kế hoạch sẽ được phóng lên không gian trong thập niên này.\n" +
                    "\n" +
                    "Sao Hỏa có thể dễ dàng nhìn từ Trái Đất bằng mắt thường. Cấp sao biểu kiến của nó đạt giá trị −2,94[19] chỉ đứng sau Sao Kim, Mặt Trăng, và Mặt Trời. Các kính thiên văn quang học trên mặt đất thường bị giới hạn trong việc phân giải các đặc điểm của hành tinh đỏ tại khoảng cách khoảng 300 km khi sao Hỏa và Trái Đất gần nhau nhất do khí quyển của Trái Đất."
    };
}
